spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test2?useSSL=false
    username: root
    password: wx110120
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  mail:
      host: smtp.163.com
      username: 18097516739@163.com
      password: wx199612
      properties:
          mail:
              smtp:
                  auth: true
                  ssl:
                      enable: true

